version: 2
updates:
  - package-ecosystem: npm
    directory: "/aws-ecs"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: 'dev'
