name: e2e
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  pwa:
    runs-on: ubuntu-latest
    env:
      AGENCY_API_URL: ${{ secrets.AgencyApiUrl }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "findy-network/findy-wallet-pwa"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: sleep # TODO: poll while the server is up
        run: sleep 360s
        shell: bash
      - name: install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          sudo ./install.sh -b /bin
      - name: download cert
        run: ./e2e/dl-cert.sh
      - name: install deps
        run: |
          npm install nightwatch@2.1.7 --legacy-peer-deps
          full_version=$(google-chrome --product-version)
          chrome_version=$(echo "${full_version%.*.*.*}")
          npm install chromedriver@$chrome_version --legacy-peer-deps
      - name: "Set cert path"
        run: |
          echo "AGENCY_TLS_PATH=$GITHUB_WORKSPACE/e2e/cert" >> $GITHUB_ENV
      - name: test
        run: npm run test:e2e
        env:
          AGENCY_URL: ${{ secrets.AgencyUrl }}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      - name: archive logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: e2e-logs
          path: tests_output
