name: e2e
on:
  repository_dispatch:

jobs:
  pwa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "findy-network/findy-wallet-pwa"
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          sudo ./install.sh -b /bin
      - name: install deps
        run: npm ci
      - name: start app
        run: CI=true npm start &
      - name: test
        run: npm run test:e2e
        env:
          AGENCY_URL: ${{ secrets.AgencyUrl }}
          AGENCY_API_URL: ${{ secrets.AgencyApiUrl }}
          AGENCY_TLS_PATH: "/cert"
