name: 'pr-comment'

on:
  pull_request:
    types: [labeled]

jobs:
  comment:
    if: ${{ github.event.label.name == 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Add comment to PR
        run: gh pr comment $PR --body "PR created by $USER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
          USER: ${{ github.event.pull_request.user.login }}
