name: test
on: push
jobs:
  test-aws-ecs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws-ecs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install CDK and typescript
        run: npm install -g aws-cdk typescript
      - name: install deps
        run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm test
  license-check-aws-ecs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws-ecs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: install deps
        run: npm ci
      - name: run check
        run: npm run licenses:check
